include: package:flutter_lints/flutter.yaml

formatter:
  page_width: 100
  trailing_commas: preserve

linter:
  rules:
    always_declare_return_types: true
    avoid_print: true
    prefer_single_quotes: true
    sort_child_properties_last: true
    prefer_interpolation_to_compose_strings: true
    avoid_types_on_closure_parameters: true
    unnecessary_lambdas: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_const_declarations: true
