include: package:flutter_lints/flutter.yaml

formatter:
  page_width: 100
  trailing_commas: preserve

linter:
  rules:
    always_declare_return_types: true
    avoid_print: true
    prefer_single_quotes: true
